### ISSUE TITLE
Temporary file in the same directory?

### ISSUE THREAD

**Issue by nomeata** [derekelkins/sws#17]
Hi,

I just noticed that during an upload, the temporary file is in `/tmp`. As it is not unlikely that the user runs `sws` on a different partition than `/tmp`, this seems suboptimal: There might not be enough space in `/tmp` (I am using `sws` right now to transfer some videos), and after the upload, moving from `/tmp` to the final destination involves actual copying, which is wasteful and can actually fail.

Most file transfer tools (webbrowsers, `rsync` etc.) put the temporary file in the destination directory.

Cheers,
Joachim

**Comment by derekelkins** [comment]
It looks like this wouldn't be difficult to change. Having run into tmpfs running out of space issues when using Android's `sdkmanager` to download Android system images, I can appreciate the frustration this can cause. I should have an update within a few days. Thanks for pointing this out.

**Comment by derekelkins** [comment]
I finally got around pushing to Hackage.
